---
title: "Untitled"
format: html
editor: visual
---

```{r message=FALSE, warning=FALSE, output = FALSE}

library(tidyverse)
library(did)

panel_df <- read_csv("agency_reassessmentyears.csv")
```

```{r}

TRA <- read_csv("./Necessary_Files/triad_reassessment_years_piv.csv")

TRA2 <- pivot_longer(TRA, cols = `2006`:`2022`, names_to = "year", values_to = "reassess_01")

#panel_data0 <- left_join(panel_data, TRA, by = "Triad")
```

```{r eval=FALSE}

panel_data1 <- panel_data %>%
  #filter(home_rule_ind == 1) %>%
  mutate(year_control = as.numeric(ifelse(year == 2015, 0,
                                ifelse(year == 2016, 1,
                                  ifelse(year == 2017, 2,
                                    ifelse(year == 2018, 3,
                                           NA
                                           )
                                ))))) %>%
  filter(between(year_control, 0, 3))
```

```{r}

panel_data1 <- df_panel %>%
 # filter(home_rule_ind == 1) %>%
  mutate(reassess_year = as.numeric(reassess_year)) %>%
  mutate(year = as.numeric(as.character(year)))

TRA2 <- TRA2 %>%
  mutate(year = as.numeric(year))

panel_data2 <- left_join(panel_data1, TRA2, by = c("triad_name" = "Triad", "year")) 

panel_data3 <- panel_data2 %>% filter(year > 2014 & year < 2020)
```

```{r}

panel_data3 <- panel_data3 %>%
  mutate(AG = case_when(
   # year == 2015 ~ 0,
    triad_name == "South" ~ 2016,
    triad_name == "City" ~ 2017,
    triad_name == "North" ~ 2018,

    T ~ 0))
panel_data3 <- panel_data3 |> filter(!is.na(AG))

table(panel_data3$AG)
table(panel_data3$year)
```

```{r}

att1 <- att_gt(
  yname = "total_final_levy",
  tname = "year",
  idname = "uniqueid",
#  xformula = ~homerule_ind,
  gname = "AG",
  data = panel_data3,
   panel = TRUE,
   allow_unbalanced_panel = T,
  control_group = "notyettreated"
)

summary(att1) 
```

Needs to switch to 1 for all periods after the treatment in the window.

```{r}

att1 <- att_gt(
  yname = "total_final_levy",
  tname = "year",
  idname = "agency_num",
  gname = "AG",
  data = panel_data3,
  panel = T,
  allow_unbalanced_panel = T,
  control_group = "notyettreated"
  #anticipation = 0
)

summary(att1)
```
