---
title: "Descriptive Stats for Levy Project Data"
format: 
  html:
    df-print: paged
    code-fold: true
    tbl-cap-location: margin
    toc: true
    toc-location: left
---


```{r setup, warning=FALSE, message=FALSE, output = FALSE}
library(modelsummary)
library(tidyverse)
library(janitor)
library(dplyr)
```


```{r}
#| label: tryFMVdata

df <- read_csv("panel_data.csv")   ## 10,374

df <- df |> filter(!minor_type %in% c("BOND", "UNIFIED", "COMM COLL", "COOK", "MISC", "MOSQUITO") ) # 9,864 obs



df <- df |> filter(year > 2009)  |>   ## 7539 obs

  mutate(tfl_pct_change = if_else(is.na(tfl_pct_change) |
                                    is.infinite(tfl_pct_change),
                                  0, tfl_pct_change) )


df <- df |> 
  select(-c(muni_name, muni_num, agency_w_hr, first6_w_hr, log_eav:reassess_lag2, 
            lag_eav_pct_change1:lag_av_pct_change2)) %>%
  mutate_at(c("home_rule_ind"), as.character)
```


```{r}
#| label: tbl-majortypeagencies-in2022-notpaneldata
#| tbl-cap: "2022 snapshot of agencies that existed. Not from balanced panel data. Agencies such as park, library, are within the MUNI/TOWNSHIP major_type."


datasummary_crosstab(major_type ~home_rule_ind, statistic = 1~1+N, data = df %>% filter(year==2022), output = "flextable")
```


```{r}
#| label: tbl-minortypeagencies-in2022-notpaneldata
#| tbl-cap: "2022 snapshot of agencies that existed. Not from balanced panel data. Agencies such as park, library, etc will be combined with their larger municipality taxing agency."

datasummary_crosstab(minor_type~home_rule_ind, data = df %>%filter(year==2022),  statistic = 1~1+N, output = "flextable")

```


# Descriptive Stats

```{r eval=FALSE}
datasummary_skim(df)
datasummary_skim(df, type  = "categorical")
```

```{r}
after2009 <- df %>% filter(year > 2009) 
df <- after2009

groupies2 <- read_csv("grouped_labels.csv") %>%          
  mutate(agency_num = str_pad(agency_num, 9, "left", "0"),
         first6 = as.character(first6), # make character
        # home_rule_ind = as.character(home_rule_ind),
         first6 = str_pad(first6, 6, "left", "0"), # add leading zeros
         first6_w_hr_ind = str_c(first6, "_", hr_ind))

grouped_manual <- df %>% 
  mutate(agency_num = str_pad(agency_num, 9, "left", "0"),
         first6 = as.character(first6), # make character
        # home_rule_ind = as.character(home_rule_ind),
         first6 = str_pad(first6, 6, "left", "0"), # add leading zeros
              lim_rate = ifelse(is.na(lim_rate), "NA", lim_rate)) |>
  left_join(groupies2,
            by = c("agency_name", "agency_num")
            ) %>% 
    filter(major_type == "MUNICIPALITY/TOWNSHIP"  
           & minor_type != "MISC"
           ) %>% 
 # filter(minor_type != "TOWNSHIP") %>%
  group_by(year, grouped_label, home_rule_ind) %>% 
  summarize(agency_name = first(agency_name),
            agency_num = first(agency_num),
            total_final_levy = sum(total_final_levy, na.rm=TRUE),
            cty_cook_eav = first(cty_cook_eav),
            cty_total_eav = first(cty_total_eav), 
            av = first(av), ## mistake fixed: was sum, now is first()
            Triad = first(Triad), 
            agency_count = n(),
            reassess_year = first(reassess_year),
            home_rule_ind = first(home_rule_ind),
            rate = sum(total_final_rate, na.rm=TRUE),
            connected_count = n(),
            lim_rate = mean(as.numeric(lim_rate), na.rm=TRUE),
            clean_name = first(clean_name)
           ) %>%
    mutate(
      conn_agency = ifelse(connected_count > 1, 1, 0),
      log_eav = log(cty_total_eav),
      log_levy = log(total_final_levy),
      log_av =  log(av),
      bundled = ifelse(agency_count > 1, 1, 0),
      uniqueid = str_c(grouped_label, "_", home_rule_ind, "_", bundled),
      panel_id = str_c(grouped_label, "_", home_rule_ind, "_", bundled, "_", lim_rate),
    first2_dig = str_sub(agency_num, 1,2),
    town = ifelse(first2_dig == "02" | agency_name == "TOWN CICERO", "Town", "Muni")) %>% 
  filter(total_final_levy > 1) %>%
  select(year, uniqueid, panel_id, everything()) %>% ungroup() 


schools <- df %>% 
  mutate(agency_num = str_pad(agency_num, 9, "left", "0"),
         first6 = as.character(first6), # make character
         home_rule_ind = as.character(home_rule_ind),
         first6 = str_pad(first6, 6, "left", "0"), # add leading zeros
         lim_rate = ifelse(is.na(lim_rate), "NA", lim_rate)) |>

  filter(major_type == "SCHOOL") %>%
  mutate(grouped_label = agency_name) %>%
  group_by(year, grouped_label, home_rule_ind) %>% 
  summarize(agency_name = first(agency_name),
            agency_num = first(agency_num),
            total_final_levy = sum(total_final_levy, na.rm=TRUE),
            cty_total_eav = first(cty_total_eav), 
            cty_cook_eav = first(cty_cook_eav),
            av = first(av), 
            Triad = first(Triad), 
            agency_count = n(),
            reassess_year = first(reassess_year),
            home_rule_ind = first(home_rule_ind),
            rate = sum(total_final_rate, na.rm=TRUE), 
            connected_count = n(),
           lim_rate = sum(as.numeric(lim_rate), na.rm=TRUE),
                       clean_name = first(clean_name)

         ) %>%
    mutate(
      conn_agency = ifelse(connected_count > 1, 1, 0),      
      log_eav = log(cty_total_eav),
      log_levy = log(total_final_levy),
      log_av =  log(av),
      bundled = ifelse(agency_count > 1, 1, 0),
      uniqueid = str_c(grouped_label, "_", home_rule_ind, "_", bundled),
      panel_id = str_c(grouped_label, "_", home_rule_ind, "_", bundled, "_", lim_rate),
    first2_dig = str_sub(agency_num, 1,2),
    town = "School") %>% 
  filter(total_final_levy > 1) %>%
  select(year, uniqueid, panel_id, everything()) %>% ungroup() 


# 94 non-HR and 76 HR in 2021, 93 non-HR and 77 HR in 2022

grouped_manual %>%  
  ungroup() %>%
  filter(year == 2022) %>%
  group_by(home_rule_ind) %>%
  summarize(count = n())
 
schools %>%  
  ungroup() %>%
  filter(year == 2022) %>%
  group_by(home_rule_ind) %>%
  summarize(count = n())


```

```{r}
grouped_manual <- rbind(grouped_manual, schools) %>% arrange(uniqueid, year)

table(grouped_manual$town)


pop2 <- readxl::read_xlsx("Necessary_Files/populationcounts_cookcountyil.xlsx")

pop2 <- pop2 %>% 
  mutate(Name = case_when(
    Name == "Forest View" ~ "Forestview",
    Name == "East Hazel Crest" ~ "East Hazelcrest",
    Name == "Hazel Crest" ~ "Hazelcrest",
    Name == "McCook" ~ "Mc Cook",
    Name == "Mount Prospect" ~ "Mt Prospect",
    Name == "Northlake" ~ "North Lake",
    TRUE~as.character(Name)
  )
  )
grouped_manual <- grouped_manual %>% 
  filter(year > 2009) %>%
  left_join(pop2, by = c("clean_name" = "Name")) 

grouped_manual <- grouped_manual %>% 
  mutate(ext_percap = case_when(
    year < 2015 ~ round(total_final_levy/pop2010),
    year >= 2015 ~ round(total_final_levy/pop2020)),
    
    taxbase_percap = case_when(
      year < 2015 ~ round(cty_cook_eav/pop2010),
      year >= 2015 ~ round(cty_cook_eav/pop2020)),
    
    tax_rate = round(total_final_levy / cty_cook_eav, digits=4) # tax rate that would come from agency_dt instead of manually calculated from PIN level.
    )

library(plm)
df_panel <- grouped_manual %>% ungroup() %>% arrange(uniqueid, year) %>%
  pdata.frame(index = c("uniqueid", "year"))

df_panel %>% group_by(uniqueid, year) %>% summarize(count = n()) %>%  filter(count > 1)
```


## Table 1: Name and Number of Taxing Agencies



```{r}
#| label: tbl-majortypeagencies-in2022-paneldata
#| tbl-cap: "2022 snapshot of agencies that existed. From panel data. Agencies such as park, library, are within the MUNI/TOWNSHIP major_type."


datasummary_crosstab(town ~home_rule_ind, statistic = 1~1+N, data = df_panel %>% filter(year==2022), output = "flextable")
```


## Table 2: Levy and Levy Growth

```{r}
#| label: tbl-levyperperson
#| tbl-cap: "Growth in the levy per person from 2010 to 2022. Uses 2010 population counts for 2010 and 2020 population counts for 2022."

# agency level growth:
levy_table <- df_panel %>% 
  filter((year == 2010 | year == 2022) & 
!is.na(ext_percap)         ) %>% 
  select(year, clean_name, ext_percap) %>% 
  pivot_wider( id_cols = c("clean_name"), names_from = "year", 
              values_from = "ext_percap") %>% 
  mutate(pct_growth = (round((`2022`-`2010`)/`2010` * 100, digits = 1) )) %>%
  arrange(desc(pct_growth))  

levy_table %>% DT::datatable(
  rownames = FALSE,
            options = list(
              dom = 't',
              scrollX = TRUE, # Enable horizontal scrolling
              columnDefs = list(
                list(targets = 1:2#, 
              #  render = JS("function(data, type, row, meta) {
             #     return type === 'display' ? data.toFixed(2) : data;
             # }")
              ),
              list(targets = 1:2, width = '50px')
              )
            ))
```

```{r}
#| label: tbl-levyperpersonmedian
#| tbl-cap: "Median levy per person from 2010 to 2022. Uses 2010 population counts for 2010 and 2020 population counts for 2020."


levy_table %>% 
  ungroup() %>%
   summarize(
            `2010 Median Levy per Capita` = median(`2010`, na.rm=TRUE),
   `2010 Levy StdDv` = (sd(`2010`, na.rm=TRUE)),
            `2022 Median Levy per Capita` = median(`2022`, na.rm=TRUE),
               `2022 Levy StdDv` = round(sd(`2022`, na.rm=TRUE), digits = 2),

            `Median Growth of Levy per Capita` = round(median(pct_growth, na.rm=TRUE), digits = 2),
            `Growth StdDv` = round(sd(pct_growth, na.rm=TRUE)),
   `# of Agencies` = n()

           ) |>
      mutate(across(where(is.numeric), round, digits = 1)) %>%

  pivot_longer(cols = c(`2010 Median Levy per Capita`:`# of Agencies`),  
               names_to = "statistic", values_to = "value") |>

  DT::datatable(rownames = FALSE)

```


```{r}
#| label: tbl-extperperson
#| tbl-cap: "**Growth in the levy per capita** from 2006 to 2022. Uses 2010 population counts for 2006 and 2020 population counts for 2022. Only Municipalities have population counts, so only they are included in the per capita tables."

df_panel %>% 
  filter(year == 2010 | year == 2022 
         ) %>% 
  filter(!is.na(ext_percap)) %>%
  select(year, clean_name, ext_percap) %>% 
  pivot_wider( id_cols = "clean_name", names_from = "year", 
              values_from = "ext_percap") %>% 
  mutate(pct_growth = (round((`2022`-`2010`)/`2010` * 100, digits = 1) ) ) %>%
  arrange(desc(`2022`)) %>% 
  DT::datatable(rownames = FALSE)
```

```{r}
#| label: tbl-extgrowth
#| tbl-cap: "**Growth in total levy** from 2010 to 2022. Uses summed `total_final_levy` for grouped munis and townships."

df_panel %>% 
  filter(year == 2010 | year == 2022 
         ) %>% 
  filter(!is.na(total_final_levy)) %>%
  select(year, grouped_label, total_final_levy) %>% 
  pivot_wider( id_cols = "grouped_label", names_from = "year", 
              values_from = "total_final_levy") %>% 
  mutate(pct_growth = (round((`2022`-`2010`)/`2010` * 100, digits = 1) ) ) %>%
  arrange(desc(pct_growth)) %>% 
  DT::datatable(rownames = FALSE)
```

## Table 3: Tax Base and Tax Base Growth

```{r}
#| label: tbl-table3
#| tbl-cap-location: top
#| tbl-cap: "Tax Base Summary Statistics (per capita), 2010 and 2022. Median change  calculated from agency level change and then locating the median value of growth."

# agency level growth:
taxbase_table <- df_panel %>% 
  filter((year == 2010 | year == 2022) & 
           !is.na(taxbase_percap )
         ) %>% 
  select(year, clean_name, taxbase_percap) %>% 
  pivot_wider( id_cols = c("clean_name"), names_from = "year", 
              values_from = "taxbase_percap") %>% 
  mutate(pct_growth = (round((`2022`-`2010`)/`2010` * 100, digits = 1) )) %>%
  arrange(desc(pct_growth)) 

taxbase_table %>% 
  ungroup() %>%
   summarize(
            `2010 Median Tax Base per Capita` = median(`2010`, na.rm=TRUE),
   `2010 Tax Base StdDv` = (sd(`2010`, na.rm=TRUE)),
            `2022 Median Tax Base per Capita` = median(`2022`, na.rm=TRUE),
               `2022 Tax Base StdDv` = round(sd(`2022`, na.rm=TRUE)),

            `Median Growth of Levy per Capita` = round(median(pct_growth, na.rm=TRUE), digits = 2),
            `Growth StdDv` = round(sd(pct_growth, na.rm=TRUE), digits = 2),
   `# of Agencies` = n()

           ) |>
      mutate(across(where(is.numeric), round)) %>%

  pivot_longer(cols = c(`2010 Median Tax Base per Capita`:`# of Agencies`),  
               names_to = "statistic", values_to = "value") |>

  DT::datatable(rownames = FALSE)

```


```{r} 
#| label: tbl-taxbasegrowth-percap
#| tbl-cap: "Growth in the **tax base per capita** from 2010 to 2022. Uses 2010 population counts for 2010 and 2020 population counts for 2022."

df_panel %>% 
  filter(year == 2010 | year == 2022) %>% 
  filter(!is.na(clean_name)) %>%
  select(year, clean_name, taxbase_percap) %>% 
  pivot_wider(id_cols = "clean_name", names_from = "year", 
              values_from = "taxbase_percap") %>% 
  mutate(pct_growth = (round((`2022`-`2010`)/`2010` * 100, digits = 1) ) ) %>%

  arrange(desc(`2022`)) %>% 
  DT::datatable(rownames = FALSE)
```


```{r}
#| label: tbl-taxbasegrowth
#| tbl-cap: "**Growth in the tax base** from 2010 to 2022. Uses 2010 population counts for 2010 and 2020 population counts for 2020."

df_panel %>% 
  filter(year == 2010 | year == 2022) %>% 
  select(year, grouped_label, cty_cook_eav) %>% 
  pivot_wider(id_cols = "grouped_label", names_from = "year", 
              values_from = "cty_cook_eav") %>% 
  mutate(pct_growth = (round((`2022`-`2010`)/`2010` * 100, digits = 1) ) ) %>%
  mutate(across(where(is.numeric), round, digits = 2)) %>%

  arrange(desc(pct_growth)) %>% 
  DT::datatable(rownames = FALSE)
```


## Table 4: Tax Rate and Tax Rate Growth

```{r}
#| label: tbl-agencylevy-taxrates
#| tbl-cap: "Tax rates shown come from the `total_final_rate` variable within PTAXSIM's internal `agency` data table. It comes from the total_final_levy / cty_cook_eav. This is the pretty much the same as the rate that would exist if the TIFs did not exist."

df_panel %>% 
  filter(year == 2010 | year == 2022) %>% 
  select(year, grouped_label, rate) %>% 
  pivot_wider(id_cols = "grouped_label", names_from = "year", values_from = "rate") %>%   
  mutate(pct_growth = (round((`2022`-`2010`)/`2010` * 100, digits = 2) ),
         `2022` = (round(`2022`, digits = 2) ) ) %>%

  arrange(desc(`2022`)) %>% 
  DT::datatable(rownames = FALSE)
```


```{r}
#| label: tbl-agencylevy-taxrates-notgrouped
#| tbl-cap: "Tax rates shown come from the `total_final_rate` variable within PTAXSIM's internal `agency` data table. It comes from the total_final_levy / cty_cook_eav. This is the pretty much the same as the rate that would exist if the TIFs did not exist. Not grouped!"

df_panel %>% 
  filter(year == 2010 | year == 2022) %>% 
  select(year, agency_name, rate) %>% 
  pivot_wider(id_cols = "agency_name", names_from = "year", values_from = "rate") %>%   
  mutate(pct_growth = (round((`2022`-`2010`)/`2010` * 100, digits = 2) ),
         `2022` = (round(`2022`, digits = 2) ) ) %>%

  arrange(desc(`2022`)) %>% 
  DT::datatable(rownames = FALSE)
```



## Models 

```{r}
library(fixest)

feols(log(total_final_levy) ~ log(cty_cook_eav)  | uniqueid + year, data = df_panel)

feols(log(total_final_levy) ~ log(cty_cook_eav)  | uniqueid + year + town, data = df_panel)


feols(log(total_final_levy)~ log(cty_cook_eav) + lag(log(cty_cook_eav), 1) + lag(log(cty_cook_eav), 2 ) | uniqueid + year, data = df_panel) 

```