---
title: "Agency Funds"
format: html
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(tidyverse)
library(ptaxsim)
library(DBI)
```

```{r}
#| eval: false

ptaxsim_db_conn <- DBI::dbConnect(RSQLite::SQLite(), 
  "C:/Users/aleaw/OneDrive/Documents/PhD Fall 2021 - Spring 2022/Merriman RA/ptax/ptaxsim.db/ptaxsim-2023.0.0.db")

agency_fund <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT *
  FROM agency_fund
  "
  )


agency_names <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT DISTINCT *
  FROM agency_info
  "
  )


agency_fund_info <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT *
  FROM agency_fund_info
  "
  )

agency_funds <- left_join(agency_fund, agency_fund_info)

agency_funds <- left_join(agency_funds, agency_names)

agency_funds %>% write_csv("agency_funds.csv")
```

```{r}
agency_funds <- read_csv("agency_funds.csv")

table(agency_funds$fund_name, agency_funds$year)

agency_funds %>% 
  filter(major_type != "COOK COUNTY" & minor_type != "SSA") %>%
  filter(year == 2022 & levy > 0) %>%
  group_by(fund_name, capped_ind) %>%
  summarize(n = n()) %>% arrange(desc(n)) %>%
  pivot_wider(names_from = capped_ind, values_from = n)


agency_funds %>% 
  filter(major_type != "COOK COUNTY" & minor_type != "SSA") %>%
  filter(year == 2022 & levy > 0) %>%
  group_by(major_type, fund_name) %>%
  summarize(n = n())

agency_funds %>% 
  filter(major_type != "COOK COUNTY" & minor_type != "SSA") %>%
  filter(year == 2022 & levy > 0) %>%
  group_by(minor_type, fund_name) %>%
  summarize(n = n())

agency_funds %>% 
  filter(fund_name == "I.M.R.F.") %>%
  filter(levy > 0 & year == 2022) %>%
  group_by(minor_type, fund_name) %>%
  summarize(n = n(),
            amount = sum(levy, na.rm = TRUE))
```
Inspect Library funds - are they library agencies or muni agencies?

```{r}
agency_funds %>% 
 # filter(year == 2022) %>%
  filter(fund_name == "LIBRARY BUILDING AND SITES" & levy > 0) %>%
  select(agency_name, everything()) %>% arrange(agency_name)
```


```{r}
agency_funds %>% 
  group_by(year, agency_name, agency_num, major_type, minor_type, capped_ind) %>%
  summarize(fundcount = n(),
            levy=sum(levy, na.rm=TRUE) ) %>%
  select(agency_name, everything()) %>% 
  arrange(agency_name)
```


```{r}
agency_funds %>% 
  filter(agency_name == "VILLAGE ") %>%
  select(agency_name, everything()) %>% arrange(agency_name)
```

