---
title: "ABFM Levy Elasticity Models"
author: "MVH & AW"
format: 
  html:
    theme: lumen
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    toc: true
    toc-location: left
    tbl-cap-location: margin
    fig-cap-location: top
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 200px
---

Data is from "helper_recode_variables.R" file, which queries and filters data from the PTAXSIM DB. It is the same data we have been using since February except when we were briefly grouping certain agencies.

```{r setup}

#| code-fold: true
#| output: false

knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(plm)
library(stars)
library(lmtest)
library(huxtable)
library(jtools)
library(modelsummary)
library(tidyverse)
library(kableExtra)

set_summ_defaults(digits = 2, pvals = FALSE, robust = "HC3")
```

```{r load_data}

#| code-fold: false
#| output: false

df <- read.csv("panel_data.csv")

df <- df %>%
  filter(major_type == "SCHOOL" | minor_type == "MUNI" | agency_name == "TOWN CICERO")

df_panel <- pdata.frame(df, index = c("agency_num", "year"))

```

# Two-Way Fixed Effects Models

## Naive Models

### Municipalities

```{r twfe_muni_naive}

#| code-fold: false

muni_subset <- subset(df_panel, minor_type == "MUNI" | agency_name == "TOWN CICERO")

naive_mod_munis <- plm(log_levy ~ log_av,
                         model = "within",
                         effect = "twoways",
                         data = muni_subset)

hr_subset <- subset(df_panel, home_rule_ind == 1 & (minor_type == "MUNI" | agency_name == "TOWN CICERO"))

nhr_subset <- subset(df_panel, home_rule_ind == 0 & (minor_type == "MUNI" | agency_name == "TOWN CICERO"))

naive_mod_muni_hr <- plm(log_levy ~ log_av,
                         model = "within",
                         effect = "twoways",
                         data = hr_subset)

naive_mod_muni_nhr <- plm(log_levy ~ log_av,
                         model = "within",
                         effect = "twoways",
                         data = nhr_subset)


muni_summ_table <- 
  export_summs(naive_mod_munis, naive_mod_muni_hr, naive_mod_muni_nhr,
               model.names = c("All Municipalities", "HR Municipalities", "NHR Municipalities"),
                                robust = "HC3",
                                statistics = c(N = "nobs", R2 = "r.squared", adj.R2 = "adj.r.squared"))

muni_summ_table <- set_caption(muni_summ_table, "Dependant Variable: ln(levy)")

print(muni_summ_table)

```
### Schools

```{r twfe_school_naive}

school_subset <- subset(df_panel, major_type == "SCHOOL")

naive_mod_school <- plm(log_levy ~ log_av,
                        model = "within",
                         effect = "twoways",
                         data = school_subset)

ele_school_subset <- subset(df_panel, major_type == "SCHOOL" 
                              & minor_type == "ELEMENTARY")

naive_mod_ele_school <- plm(log_levy ~ log_av,
                            model = "within",
                            effect = "twoways",
                            data = ele_school_subset)

second_school_subset <- subset(df_panel, minor_type == "SECONDARY")

naive_mod_second_school <- plm(log_levy ~ log_av,
                               model = "within",
                               effect = "twoways",
                               data = second_school_subset)

school_table <- export_summs(naive_mod_school, naive_mod_ele_school, naive_mod_second_school,
             model.names = c("All Schools", "Elementary Schools", "Secondary Schools"),
             robust = "HC3",
             statistics = c(N = "nobs", R2 = "r.squared", adj.R2 = "adj.r.squared"))

school_table <- set_caption(school_table, "Dependant Variable: ln(levy)")

print(school_table)

```
