---
title: "DiD Attempt"
subtitle: "Using Assessed Value"
author: "AWM & MVH"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float: yes
    df_print: paged
    code_folding: hide
---

```{r setup, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(tidyverse)
library(DBI)
#library(data.table)
#library(ggspatial)
#library(gstat)
#library(here)
#library(httr)
#library(jsonlite)
library(ptaxsim)
#library(sf)
library(stars)
#library(glue)
library(lmtest)
library(huxtable) # for summ() and regression output formatting
# Create the DB connection with the default name expected by PTAXSIM functions
library(jtools)
library(plm) #for fixed effects
library(modelsummary)
library(dplyr)
#install.packages("did")
library(did)

ptaxsim_db_conn <- DBI::dbConnect(RSQLite::SQLite(), "C:/Users/aleaw/OneDrive/Documents/PhD Fall 2021 - Spring 2022/Merriman RA/ptax/ptaxsim.db/ptaxsim-2021.0.4.db")
#set_summ_defaults(digits = 2, pvals = FALSE, robust = "HC3" )


# Data notes for pct_res: 
# muni av and eav are calculated from the pin data table in ptaxsim. It is BEFORE exemptions and includes any EAV that is above the frozen TIF EAV, frozen EAV, and EAV outside of TIF tax codes.
# percentages for land use are also before exemptions and do not consider any EAV that would go to a TIF increment

#groupies <- readxl::read_excel("./grouped_munis_manual_entry.xlsx")

muni_agency_names <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT DISTINCT agency_num, agency_name, minor_type
  FROM agency_info
  WHERE minor_type = 'MUNI'
  OR agency_num = '020060000'
  "
  ) %>% 
  mutate(first6 = str_sub(agency_num,1,6),
        # first5 = str_sub(agency_num,1,5)
         ) %>%
  select(-minor_type)

```

From agency.R code in ptaxsim Gitlab "The levy of each jurisdiction is reported by the Cook County Clerk's Office. URL here: <https://www.cookcountyclerkil.gov/service/tax-extension-and-rates>


# Data Gathering and Cleaning



## Manipulated Variables

```{r message = FALSE, warning = FALSE}
source("helper_recode_variables.R")
```

```{r}

library(dplyr)

all_agencies <- recoded_data

panel_data <-pdata.frame(recoded_data, index = c("agency_num", "year"))


hr_agencies <- panel_data %>% filter(home_rule_ind == 1)
#hr_agencies_bal <- make.pbalanced(hr_agencies)

table(hr_agencies$year)
```



# From 2014 to 2018


```{r}
library(dplyr)

after2014_hr <- recoded_data %>% 
  ungroup() %>% 
    mutate(cty_cook_eav = total_final_levy / total_final_rate,
         av = cty_cook_eav / eq_factor_final) %>%
  mutate(year_num = as.numeric(as.character(year)) ) %>% 
  filter(year_num > 2014 & year_num  < 2019) %>%
    filter(major_type == "MUNICIPALITY/TOWNSHIP" # | major_type == "MISCELLANEOUS"
           & minor_type != "MISC"
           ) %>%  
  filter(home_rule_ind == 1) %>% 
  #group_by(year, grouped_label, home_rule_ind, lim_rate) %>% 
  # summarize(agency_name = first(agency_name),
  #           agency_num = first(agency_num),
  #           total_final_levy = sum(total_final_levy, na.rm=TRUE)+1,
  #           cty_total_eav = first(cty_total_eav), 
  #           av = sum(av, na.rm=TRUE),
  #           Triad = first(Triad), 
  #           agency_count = n(),
  #           reassess_year = first(reassess_year),
  #           home_rule_ind = first(home_rule_ind)) %>% 
    left_join(muni_agency_names) %>% 
    #select(-c(Column1, `Most recent reassessed`)) %>% 
    # mutate(
    #   log_eav = log(cty_total_eav),
    #   log_levy = log(total_final_levy),
    #   bundled = ifelse(agency_count > 1, 1, 0),
    #   uniqueid = str_c(grouped_label, "_", home_rule_ind, "_", bundled),
    #   panel_id = str_c(grouped_label, "_", home_rule_ind, "_", bundled, "_", lim_rate),
    # first2_dig = str_sub(agency_num, 1,2),
    # town = ifelse(first2_dig == "02" | agency_name == "TOWN CICERO", "Town", "Muni")) %>% 
  filter(total_final_levy > 1) %>%
  select(year, agency_name, everything())

 after2014_hr %>%  
  ungroup() %>%
  group_by(home_rule_ind, year) %>%
  summarize(count = n())
```


```{r}
after2014_hr <- after2014_hr %>% group_by(agency_name) %>% mutate(year_count = n()) %>% ungroup() %>% filter(year_count == 4)
table(after2014_hr$year)
```


93 HR if only majortype munis is included. 

```{r}
after2014_hr %>% ggplot() + 
  geom_line(aes(x=year,y=total_final_levy, group = agency_name, alpha = .5, color = Triad)) + 
  theme_classic()


after2014_hr %>% ggplot() + 
  geom_point(aes(x=log(av), y = log(total_final_levy), color = agency_name)) + theme(legend.position = "none")

after2014_hr %>% ggplot() + 
  geom_point(aes(x=log(av), y = log(total_final_levy), color = agency_name, shape = year)) + theme(legend.position = "none")


after2014_hr %>% ggplot() + 
  geom_point(aes(x=year, y=av,# color = home_rule_ind, 
                 alpha = .1)) +
  geom_line(aes(x=year, y = av, group = agency_name, alpha = .1, color = Triad)) +
  geom_smooth(aes(x=year, y=av, # 
                  color = Triad, se=FALSE, size = 2)) + 
  theme_classic() + 
  labs(title = "Assessment impact on AV",
       subtitle = "Years shown are Tax Years (Reassessment year + 1)", 
       caption = "North Triad was reasessed in 2015,
       South Triad was reassessed in 2016,
       Chicago was reassessed in 2017.")

after2014_hr %>% ggplot() + 
  geom_point(aes(x=year, y=total_final_levy,# color = home_rule_ind, 
                 alpha = .1)) +
  geom_line(aes(x=year, y = total_final_levy, group = agency_name, alpha = .1)) +
  geom_smooth(aes(x=year, y=total_final_levy, # 
                  group = Triad,
                 # group = grouped_w_hr_ind, 
                  color = Triad), se=FALSE, size = 2) + 
  theme_classic()

after2014_hr %>% ggplot() + 
  geom_point(aes(x=year, y=av,# color = home_rule_ind, 
                 alpha = .1)) +
  geom_line(aes(x=year, y = av, group = agency_name, alpha = .1)) +
  geom_smooth(aes(x=year, y=av, # 
                  group = Triad,
                 # group = grouped_w_hr_ind, 
                  color = Triad), se=FALSE, size = 2) + 
  theme_classic()


```

```{r}
after2014_hr %>% 
  filter(Triad != "City") %>%
  ggplot() + 
  geom_line(aes(x=year,y=total_final_levy, group = agency_name, alpha = .5, color = Triad)) + 
  theme_classic()


after2014_hr %>% 
    filter(Triad != "City") %>%
ggplot() + 
  geom_point(aes(x=log(av), y = log(total_final_levy), color = agency_name)) + theme(legend.position = "none")

after2014_hr %>% 
    filter(Triad != "City") %>%
ggplot() + 
  geom_point(aes(x=log(av), y = log(total_final_levy), color = agency_name, shape = year)) + theme(legend.position = "none")


after2014_hr %>% 
    filter(Triad != "City") %>%
ggplot() + 
  geom_point(aes(x=year, y=av,# color = home_rule_ind, 
                 alpha = .1)) +
  geom_line(aes(x=year, y = av, group = agency_name, alpha = .1, color = Triad)) +
  geom_smooth(aes(x=year, y=av, # 
                  color = Triad, se=FALSE, size = 2)) + 
  theme_classic() + 
  labs(title = "Assessment impact on AV",
       subtitle = "Years shown are Tax Years (Reassessment year + 1)", 
       caption = "North Triad was reasessed in 2015,
       South Triad was reassessed in 2016,
       Chicago was reassessed in 2017.")

after2014_hr %>% 
    filter(Triad != "City") %>%
ggplot() + 
  geom_point(aes(x=year, y=total_final_levy,# color = home_rule_ind, 
                 alpha = .1)) +
  geom_line(aes(x=year, y = total_final_levy, group = agency_name, alpha = .1)) +
  geom_smooth(aes(x=year, y=total_final_levy, # 
                  group = Triad,
                 # group = grouped_w_hr_ind, 
                  color = Triad), se=FALSE, size = 2) + 
  theme_classic()

after2014_hr %>%   filter(Triad != "City") %>%

  ggplot() + 
  geom_point(aes(x=year, y=av,# color = home_rule_ind, 
                 alpha = .1)) +
  geom_line(aes(x=year, y = av, group = agency_name, alpha = .1)) +
  geom_smooth(aes(x=year, y=av, # 
                  group = Triad,
                 # group = grouped_w_hr_ind, 
                  color = Triad), se=FALSE, size = 2) + 
  theme_classic()


```

# DID 
```{r}

TRA <- read_csv("./Necessary_Files/triad_reassessment_years_piv2.csv") %>% 
  select(Triad, `2014`:`2018`)

TRA2 <- TRA %>% pivot_longer(cols = `2014`:`2018`, names_to = "year", values_to = "reassess_01")

panel_data0 <- recoded_data %>%
  filter(minor_type == "MUNI") %>%
  filter(home_rule_ind == 1) %>%
 # mutate(reassess_year = as.numeric(reassess_year)) %>%
  mutate(agency_num = as.factor(agency_num)) %>%
  mutate(year_num = as.character(year),
         year = as.factor(year))

panel_data1 <- panel_data0 %>% filter(year_num > 2014 & year_num < 2019)


panel_data2 <- left_join(panel_data1, TRA2, by = c("Triad", "year_num" = "year"))
table(panel_data2$year)

#panel_data2 <-pdata.frame(panel_data2, index = c("agency_num", "year"))

panel_data2 <- panel_data2 %>% 
  mutate(total_final_levy = as.numeric(total_final_levy),
         reassess_01 = as.numeric(reassess_01),
    year_num = as.numeric(as.character(year)),
         id = as.numeric(agency_num)) %>%
  group_by(agency_num) %>%
  mutate(year_count = n()) %>%
  ungroup() %>%
  filter(year_count ==4)
table(panel_data2$year)

table(panel_data2$reassess_01)

is.pbalanced(panel_data2)
panel_data3 <-pdata.frame(panel_data3, index = c("agency_num", "year_num"))


panel_data3 <- panel_data2 %>% 
  select(total_final_levy, reassess_01, year_num, id, av, Triad, agency_num) %>%
  mutate(triad_group = as.numeric(ifelse(Triad=="City",1, ifelse(Triad=="North",2, "South"))) ) #%>%
 # filter(total_final_levy>0 & !is.na(triad_group) & !is.na(year_num) ) %>% filter(Triad!="City")

  

att1 <- att_gt(
  yname = "total_final_levy",
  tname = "year_num",
  idname = "id",
  gname = "reassess_01",
  #xformla = ~av,
  data = panel_data3 #,
#  panel = FALSE,
 # control_group = "notyettreated"
)

summary(att1)
```

```{r }

after2014_hr2 <- after2014_hr %>%left_join(TRA2, by = c("Triad", "year")) %>%
  mutate(year = as.numeric(as.character(year)),
         agency_num = as.numeric(agency_num)) %>%
   mutate(triad_group = as.numeric(ifelse(Triad=="City",1, ifelse(Triad=="North",2, "South"))) )


example_attgt_altcontrol <- att_gt(yname = "total_final_levy",
                                   tname = "year",
                                   idname = "agency_num",
                                   gname = "Triad_num",
                                   data = after2014_hr,
                                   control_group = "notyettreated",

                                   )
```


```{r}
class(all_agencies$year)

all_agencies %>% 
  mutate(cty_cook_eav = total_final_levy / total_final_rate,
         av = cty_cook_eav / eq_factor_final) %>%
  mutate( year = as.numeric(as.character((year) ) )) %>% filter(home_rule_ind == 1 & year > 2012) %>%
group_by(agency_name) %>% mutate(year_count = n())%>% ungroup() %>%
  #mutate(year = as.factor())
 filter(year_count == 10) %>% 
  ggplot() + 
  geom_point(aes(x=year, y=av,# color = home_rule_ind, 
                 alpha = .1)) +
  geom_line(aes(x=year, y = av, group = agency_name, alpha = .1)) +
  geom_smooth(aes(x=year, y=av, # 
                  group = Triad,
                 # group = grouped_w_hr_ind, 
                  color = Triad), se=FALSE, size = 2) + 
  theme_classic()
```



## OLS and FE 


### Event Studies


```{r av-lmdata-triad2014, eval=FALSE}

#detach("package:dplyr", unload = TRUE)

grouped_munis <- hr_agencies
library(dplyr)
grouped_munis <- grouped_munis %>% 
  mutate(#yearly_change = log_eav-eav_lag1,
         #yearly_chang_perc =(log_eav-eav_lag1)/eav_lag1,
         eav_change = cty_total_eav - cty_eav_lag,
         eav_change_pct = ((cty_total_eav - cty_eav_lag)/cty_eav_lag),
         av_change = av - av_lag,
         av_pct_change = (av-av_lag)/av_lag
       ) %>%
  mutate(up_down  = ifelse(eav_change > 0, "increased", "decreased"),
         North_reassess = ifelse(reassess_year == "2020", "N_reassess", "no_assess"))


detach("package:dplyr", unload = TRUE)

# All Agencies-Agency & Year FE"
grouped_model<- lm(log(total_final_levy) ~ log(cty_total_eav), 
                    data = grouped_munis)






grouped_cleannames_withHRind <- lm(log(total_final_levy) ~ log(cty_total_eav)+ log(cty_total_eav):Triad, 
                          data = grouped_munis)

#summary(grouped_cleannames_withHRind)

grouped_cleannames_withHRind_lagged <- plm(log(total_final_levy) ~ log(cty_total_eav)+ log(cty_total_eav):Triad + lag(log(cty_total_eav),1) + lag(log(cty_total_eav),2), 
                          data = grouped_munis)

#summary(grouped_cleannames_withHRind_lagged)

grouped_cleannames_lag <- plm(log(total_final_levy) ~ log(cty_total_eav) + lag(log(cty_total_eav),1) + lag(log(cty_total_eav),2),
                              data = grouped_munis)

grouped_cleannames_lag2 <- plm(log(total_final_levy) ~ log(cty_total_eav) + lag(log(cty_total_eav),1) + lag(log(cty_total_eav),2)+log(cty_total_eav):Triad + lag(log(cty_total_eav),1):Triad  + lag(log(cty_total_eav),2):Triad ,
                              data = grouped_munis)
#summary(grouped_cleannames_lag2)


model_names <- c(grouped_model = "Grouped manually, Summed Levies", 
                 grouped_cleannames_lag = "with Lags",
                 grouped_cleannames_withHRind = "with Triad Indicator",
                 grouped_cleannames_withHRind_lagged = "Triad indacator with Lags",
                grouped_cleannames_lag2 = "Triad interact with both Lags") # has Chicago


# plot(grouped_model)


export_summs(grouped_model, grouped_cleannames_lag,  grouped_cleannames_withHRind, grouped_cleannames_withHRind_lagged, grouped_cleannames_lag2, robust = "HC3",  model.names = model_names, statistics = c(N = "nobs", R2 = "r.squared", adj.R2 = "adj.r.squared"))



```


```{r av-laggedlevy-triad2014, eval=FALSE, include=FALSE}

#detach("package:dplyr", unload = TRUE)


library(dplyr)
grouped_munis <- grouped_munis %>% 
  mutate(yearly_change = log_eav-eav_lag1,
         yearly_chang_perc =(log_eav-eav_lag1)/eav_lag1,
         eav_change = cty_total_eav - cty_eav_lag,
         eav_change_pct = ((cty_total_eav - cty_eav_lag)/cty_eav_lag),
         av_change = av - av_lag,
         av_pct_change = (av-av_lag)/av_lag
       ) %>%
  mutate(up_down  = ifelse(eav_change > 0, "increased", "decreased"),
         North_reassess = as.factor(ifelse(reassess_year == "2020", "N_reassess", "no_assess")))


detach("package:dplyr", unload = TRUE)

# All Agencies-Agency & Year FE"
grouped_model<- lm(log(total_final_levy) ~ lag(log(total_final_levy)), 
                    data = grouped_munis)






grouped_cleannames_withHRind <- lm(log(total_final_levy) ~ log(av)+ log(total_final_levy), 
                          data = grouped_munis)

#summary(grouped_cleannames_withHRind)

grouped_cleannames_withHRind_lagged <- lm(log(total_final_levy) ~ log(av)+ log(total_final_levy) + Triad, 
                          data = grouped_munis)


grouped_cleannames_lag <- lm(log(total_final_levy) ~ log(av) + lag(log(av),1) + lag(log(av),2),
                              data = grouped_munis)

grouped_cleannames_lag2 <- lm(log(total_final_levy) ~ log(av) + lag(log(av),1) + lag(log(av),2)+ log(av):Triad + lag(log(av),1):Triad  + lag(log(av),2):Triad ,
                              data = grouped_munis)


model_names <- c(grouped_model = "Grouped manually, Summed Levies", 
                 grouped_cleannames_lag = "with Lags",
                 grouped_cleannames_withHRind = "with Triad Indicator",
                 grouped_cleannames_withHRind_lagged = "Triad indacator with Lags",
                grouped_cleannames_lag2 = "Triad interact with both Lags") # has Chicago


# plot(grouped_model)


export_summs(grouped_model, grouped_cleannames_lag,  grouped_cleannames_withHRind, grouped_cleannames_withHRind_lagged, grouped_cleannames_lag2, robust = "HC3",  model.names = model_names, statistics = c(N = "nobs", R2 = "r.squared", adj.R2 = "adj.r.squared"))



```


# 1-year Change

```{r eval=FALSE}
pct <- function(x) {x / lag(x) - 1}

recoded_data %>% 
  group_by(year, agency_w_hr) %>% 
  mutate_at(av, funs=pct) 

z %>%
  group_by(VERTICAL) %>% 
  arrange(YEAR, .by_group = TRUE) %>%
  mutate(pct_change = (Profit/lag(Profit) - 1) * 100)
```


